language: node_js
node_js:
  - "0.10"
  - "0.12"
before_script:
  - npm install -g .
  - npm install -g jake
  - npm install -g titanium
  - mkdir ~/.titanium
  - cp ./cli_config.json ~/.titanium/config.json